### ISSUE TITLE
Investigate missing debug information in SAVE-cloud

### ISSUE THREAD

**Issue by akuleshov7** [diktat-static-analysis/save-cloud#512] opened 2021-12-20 17:06 UTC
In some cases we receive 404 for getting additional information, for example: http://saveourtool.com/#/LLVM.org/Clang-tidy/history/execution/67/details/Clang%20Tidy%20Tests/WarnPlugin/checkers/abseil-duration-conversion-cast.cpp

Some executions are getting lost: 
![image](https://user-images.githubusercontent.com/58667063/146805001-9d3932ec-38c6-4d18-ba61-942010d9c61b.png)

I would say that it is okay if ALL executions would be lost, but we lose it only partially

**Comment by petertrr** [comment] 2021-12-21 06:17
```
ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [b9937425-2]  500 Server Error for HTTP POST "/api/files/debug-info?agentId=86e48d807436c3c1c70d82d378c46bb9e56e6c509324109034fb6e697c16d977"
org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144
```
Similar to #298, but it happens for debug info too. We should split this data, and/or try to finish #329 (but it turned out, that there is no ready-to-use client-side encoding, only decoding for server-created data)

**Comment by petertrr** [comment] 2021-12-23 07:08
Closing as a duplicate of #298

**Closed by petertrr** 2021-12-23 07:08 UTC
Labels: bug, duplicate
